export enum BADGE_CRITERIA_ENUM {
  TOTAL_QUESTION_CREATED = "TOTAL_QUESTION_CREATED",
  TOTAL_QUESTION_VIEWS = "TOTAL_QUESTION_VIEWS",
  TOTAL_QUESTION_UPVOTES = "TOTAL_QUESTION_UPVOTES",
  TOTAL_ANSWER_CREATED = "TOTAL_ANSWER_CREATED",
  TOTAL_ANSWER_UPVOTES = "TOTAL_ANSWER_UPVOTES",
}

export const BADGE_CRITERIA = {
  [BADGE_CRITERIA_ENUM.TOTAL_QUESTION_CREATED]: {
    BRONZE: 10,
    SILVER: 50,
    GOLD: 100,
  },
  [BADGE_CRITERIA_ENUM.TOTAL_QUESTION_VIEWS]: {
    BRONZE: 1000,
    SILVER: 10000,
    GOLD: 100000,
  },
  [BADGE_CRITERIA_ENUM.TOTAL_QUESTION_UPVOTES]: {
    BRONZE: 10,
    SILVER: 50,
    GOLD: 100,
  },
  [BADGE_CRITERIA_ENUM.TOTAL_ANSWER_CREATED]: {
    BRONZE: 10,
    SILVER: 50,
    GOLD: 100,
  },
  [BADGE_CRITERIA_ENUM.TOTAL_ANSWER_UPVOTES]: {
    BRONZE: 10,
    SILVER: 50,
    GOLD: 100,
  },
};
